### ISSUE TITLE
Missing Parameter (missing_parameter) : username while running in Jenkins

### ISSUE THREAD

**Issue by asitroy09** [zaproxy/community-scripts#107]
Hi,

I am trying to run ZAP Active scan from Jenkins.  Following errors coming even after trying multiple options.

[ZAP Jenkins Plugin] USER CREATION
4300 [ZAP-ProxyThread-10] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/xml/users/action/setAuthenticationCredentials/] from [127.0.0.1]:
Missing Parameter (missing_parameter) : username
	at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(ApiUtils.java:83)
	at org.zaproxy.zap.authentication.GenericAuthenticationCredentials$1.handleAction(GenericAuthenticationCredentials.java:152)
	at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(UsersAPI.java:217)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:745)
ERROR: org.zaproxy.clientapi.core.ClientApiException: Missing Parameter
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:32)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:312)
	at org.zaproxy.clientapi.gen.Users.setAuthenticationCredentials(Users.java:112)
	at org.jenkinsci.plugins.zap.ZAPDriver.setUpUser(ZAPDriver.java:1610)
	at org.jenkinsci.plugins.zap.ZAPDriver.setUpAuthentication(ZAPDriver.java:1717)
	at org.jenkinsci.plugins.zap.ZAPDriver.executeZAP(ZAPDriver.java:1184)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:448)
	at org.jenkinsci.plugins.zap.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:436)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2665)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:63)
	at java.lang.Thread.run(Unknown Source)

**Comment by kingthorin** [comment]
According to https://wiki.jenkins.io/display/JENKINS/zap+plugin#zapplugin-Questions/Troubleshooting support for the Jenkins plugin is here:  https://groups.google.com/forum/#%21forum/zaproxy-jenkins which seems like a much better place than the community-scripts repo.
